### ISSUE TITLE
Rows get merged incorrectly with certain JSON

### ISSUE THREAD

**Issue by fastfedora** [bradjasper/ImportJSON#3]
The JSON below gets parsed as three rows when it should get parsed as four rows. See the expected and actual results below the JSON. 

The problem lies in the `parseData_` function. The `rowIndex` is not being incremented correctly. A partial solution is to add `rowIndex++;` on line 284 of version 1.2.0, but this should be tested to make sure it doesn't break other JSON inputs, and doesn't completely solve the problem.
## JSON Input

```
[
   { 
      "id":"123" 
   },

   { 
      "id":"457",
      "jobs": [
         {
            "rate":"5.45"
         },
         {
            "rate":"5.75",
            "country":"US"
         }
      ]
   },

   {
      "id":"458",
      "jobs": [
         {
            "rate":"5.55",
            "feedback":
               {
                  "score":"5.0"
               }
         }
      ]
   }
]
```
## Expected Results

<table>
<tr><td>Id</td><td>Jobs Rate</td><td>Jobs Country</td><td>Jobs Feedback Score</td></tr>
<tr><td>123</td><td></td><td></td><td></td></tr>
<tr><td>457</td><td>5.45</td><td></td><td></td></tr>
<tr><td>457</td><td>5.75</td><td>US</td><td></td></tr>
<tr><td>458</td><td>5.55</td><td></td><td>5.0</td></tr>
</table>

## Actual Results

<table>
<tr><td>Id</td><td>Jobs Rate</td><td>Jobs Country</td><td>Jobs Feedback Score</td></tr>
<tr><td>123</td><td></td><td></td><td></td></tr>
<tr><td>457</td><td>5.45</td><td></td><td></td></tr>
<tr><td>458</td><td>5.55</td><td>US</td><td>5.0</td></tr>
</table>

**Comment by athace** [comment]
As of 1.2.1 I still dont get the expected results.
Had to modify the rowIndex incremental conditions. For most of my cases the i > 0 check messes up my table, because basically the next row is getting written on the first one. Can I ask what is the purpose of this condition?

**Comment by fastfedora** [comment]
The i > 0 is there to prevent incrementing the row index when parsing the first row of the array. But there could easily be a bug there. I don't have time right now to debug this, but if I get someone to work on this project, I'll let them know.

**Comment by parthakkar** [comment]
Did anybody ever get a solution to this? I believe that I am experiencing the same issue. Thanks

**Comment by parthakkar** [comment]
I don't know if this is related, but for some reason, the first object in my JSON pull is being omitted from the data.  So essentially id=123 won't import into the sheet. The query that I am using is **"/data/"**. But even when I omit the query and import all, it still won't add id=123. Anybody know what I'm doing wrong? Thanks!

My JSON looks like this:

`{"status_code":200,"message":"OK","data":{"products":[
   { 
      "id":"123" 
   },

   { 
      "id":"457",
      "jobs": [
         {
            "rate":"5.45"
         },
         {
            "rate":"5.75",
            "country":"US"
         }
      ]
   },

   {
      "id":"458",
      "jobs": [
         {
            "rate":"5.55",
            "feedback":
               {
                  "score":"5.0"
               }
         }
      ]
   }]
]}`

**Comment by bradjasper** [comment]
Believe this was fixed with https://github.com/bradjasper/ImportJSON/pull/18

**Comment by lazmo88** [comment]
I am still facing the same issue, the data gets imported to the sheet, however last  3 values are added to a new row. I am using following options: "noInherit,noHeaders". Before using noInherit the output was complete on the 2nd row, whereas 1st row was missing the 3 last values.

=ImportJSONViaPost(URL,json_payload,"contentType=json/application","/resultCode,/MC/balance,/MC/validity,/MC/SMS,/MC/status,/MC/stop,/package/balance,/package/validity,/package/packageCapacity","noInherit,noHeaders")

Any ideas what could be wrong here?

![git](https://user-images.githubusercontent.com/25498972/38460916-00329d22-3ad5-11e8-8707-bcf906543f17.PNG)
